# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('score', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Titles',
        ),
    ]
