# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0002_auto_20170528_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='score',
            field=models.PositiveIntegerField(),
        ),
    ]
